### ISSUE TITLE
support custom client TLS certificate (from local disk or w/e) in MITM socket

### ISSUE THREAD

**Issue by GlenDC** [unblocked-web/agent#19]
For an official integration we are required to use a TLS client certificate (<https://blog.cloudflare.com/introducing-tls-client-auth/>) for a target. As we already have our custom MITM socket in Agent (used by Hero), I imagine we should be able to inject in that Go TLS client a certificate. I mean technically it is possible, it's just going to be a matter on how we'll want to approach this?

I think the easiest might be if we can just pass a (local FS) filePath or so? 

Open to discuss and brainstorm this with you.

We require this feature if we want to start using Hero in production.
For one and only one integration, but an important one.

**Comment by blakebyrnes** [comment]
@GlenDC My preferred first step for this is to try to establish a tls connection strictly using the underlying uTLS library in go. If you can provide a code snippet that does so, I think we can start to figure out how to put in the other parts

**Comment by GlenDC** [comment]
@blakebyrnes you can find a snippet at <https://gist.github.com/ncw/9253562#file-client-go-L12-L17>.

All we would therefore really just need is to be able to pass the paths to the cert files on local disk for that hero instance.

And yes I was indeed talking about using the underlying uTLS library (which is the forked TLS library) to do that.

---

That being said. I think I no longer need it, as apparently for browser-purposes we do not actually use it for that target, only for data purposes which does not use a browser for that target. So all is good on my end.

That being said, it can never the less be a useful feature and that could also open the door to some other non-fp related TLS settings that could be useful.

**Comment by blakebyrnes** [comment]
Ok, sounds good. I do think we should still try out a snippet against a known target using client certificates directly with uTLS. I'm not sure how client certificates interacts with any of the modifications (like certificate compression) that uTLS makes to the regular go library. But this is probably of lesser importance if you don't need it. I don't need it... so this will remain unused for now if we add it.

**Comment by GlenDC** [comment]
True true.

So let's perhaps just close it for now.
